version: '3.8'

services:
  haskell-master:
    image: distributed-haskell:latest
    networks:
      - haskell-network
    command: ["cabal", "run", "master"]
    container_name: haskell-master

  haskell-worker:
    image: distributed-haskell:latest
    networks:
      - haskell-network
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    container_name: haskell-worker

networks:
  haskell-network:
    driver: bridge
