version: '3'

networks:
  my_network:
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  master:
    image: distributed-haskell
    networks:
      my_network:
        ipv4_address: 192.168.1.1
    command: cabal run master

  node2:
    image: distributed-haskell
    networks:
      my_network:
        ipv4_address: 192.168.1.2
    command: cabal run worker

  node3:
    image: distributed-haskell
    networks:
      my_network:
        ipv4_address: 192.168.1.3
    command: cabal run worker

  node4:
    image: distributed-haskell
    networks:
      my_network:
        ipv4_address: 192.168.1.4
    command: cabal run worker

  node5:
    image: distributed-haskell
    networks:
      my_network:
        ipv4_address: 192.168.1.5
    command: cabal run worker
